apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        apps: helloworld
     spec:
       containers:
         - name: k8s-demo
           image: arjunachari12/k8s-demo
