apiVersion: v1
kind: Pod
metada:
  name: nodehelloword.example.com
  label:
    app: helloworld
   spec:
     containers:
     - name: k8s-demo
       image: arjunachari12/k8s-demo
       ports:
       - name: nodejs-port
         containerPort: 3000
     
