apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  ports:
  - port: 31002
    nodePort: 31009
    targetPort: nodejs-port
    protocol: TCP
  selector:
    app: redis
  type: LoadBalance
