apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-premium-reatin-sc
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion
parameters:
  storageaccounttype: Premium_LRS
  kind: managed
